"""change bookmarkrecipes to join table

Revision ID: 11bcd884cdb3
Revises: 604bd3e25893
Create Date: 2023-06-17 13:50:58.625840

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '11bcd884cdb3'
down_revision = '604bd3e25893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarkrecipes',
    sa.Column('recipes', sa.Integer(), nullable=False),
    sa.Column('bookmarks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmarks'], ['bookmarks.id'], ),
    sa.ForeignKeyConstraint(['recipes'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipes', 'bookmarks')
    )
    op.drop_table('bookmarksrecipes')
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarksrecipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('bookmark_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id', 'recipe_id', 'bookmark_id')
    )
    op.drop_table('bookmarkrecipes')
    # ### end Alembic commands ###